# Lab 3: NumPy Basics

**Course:** Data Science and Big Data Analytics  

This notebook completes the Lab 3 NumPy Basics assignment.  
Each section includes Python/NumPy code, comments, and visible output for grading.


In [1]:
# Import NumPy library
import numpy as np

# Set random seed so the random output is reproducible
np.random.seed(42)

## Part 1: Working with Arrays

### Task 1
Create a NumPy array named `a` with shape `(3, 4)`.


In [2]:
# 1. Create a NumPy array named a with shape (3, 4)
a = np.array([
    [3, 8, 15, 2],
    [2, 10, 5, 3],
    [4, 0, 2, 4]
])

print("Array a:")
print(a)

Array a:
[[ 3  8 15  2]
 [ 2 10  5  3]
 [ 4  0  2  4]]


### Task 2
Print the shape of the array `a`.


In [3]:
# 2. Print the shape of array a
print("Shape of array a:")
print(a.shape)

Shape of array a:
(3, 4)


### Task 3
Print the number of dimensions of the array.


In [4]:
# 3. Print the number of dimensions
print("Number of dimensions of array a:")
print(a.ndim)

Number of dimensions of array a:
2


### Task 4
Use the built-in `len()` function on `a`.


In [5]:
# 4. Use built-in len() function
print("Result of len(a):")
print(len(a))

Result of len(a):
3


### Task 5
Based on the shape of the array, determine the number of dimensions and the length.


In [6]:
# 5. Explanation based on shape
print("The shape of a is:", a.shape)
print("Because the shape has two values, the array has 2 dimensions.")
print("The first value in the shape is 3, so len(a) returns 3.")
print("This means len(a) gives the number of rows in this 2D array.")

The shape of a is: (3, 4)
Because the shape has two values, the array has 2 dimensions.
The first value in the shape is 3, so len(a) returns 3.
This means len(a) gives the number of rows in this 2D array.


## Part 2: Array Creation with NumPy

### Task 6
Create a 1D NumPy array with values from 2 to 5, inclusive.


In [7]:
# 6. Create a 1D NumPy array with values from 2 to 5 inclusive
array_2_to_5 = np.arange(2, 6)

print("1D array with values from 2 to 5 inclusive:")
print(array_2_to_5)

1D array with values from 2 to 5 inclusive:
[2 3 4 5]


### Task 7
Create a 1D array with 10 equally spaced values between 2 and 5, inclusive.


In [8]:
# 7. Create a 1D array with 10 equally spaced values between 2 and 5
linspace_array = np.linspace(2, 5, 10)

print("1D array with 10 equally spaced values between 2 and 5:")
print(linspace_array)

1D array with 10 equally spaced values between 2 and 5:
[2.         2.33333333 2.66666667 3.         3.33333333 3.66666667
 4.         4.33333333 4.66666667 5.        ]


### Task 8
Create a 4 x 4 array filled with ones.


In [9]:
# 8. Create a 4 x 4 array filled with ones
ones_array = np.ones((4, 4))

print("4 x 4 array filled with ones:")
print(ones_array)

4 x 4 array filled with ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Task 9
Create a 6 x 6 identity matrix.


In [10]:
# 9. Create a 6 x 6 identity matrix
identity_matrix = np.eye(6)

print("6 x 6 identity matrix:")
print(identity_matrix)

6 x 6 identity matrix:
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


### Task 10
Create the following diagonal matrix using a single NumPy command:

```python
[[1, 0, 0],
 [0, 2, 0],
 [0, 0, 3]]
```


In [11]:
# 10. Create diagonal matrix using a single NumPy command
diagonal_matrix = np.diag([1, 2, 3])

print("Diagonal matrix:")
print(diagonal_matrix)

Diagonal matrix:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Task 11
Use `np.random.randn()` to create a `(3, 5)` array with random numbers from a standard normal distribution.


In [12]:
# 11. Create a (3, 5) array from standard normal distribution
random_array = np.random.randn(3, 5)

print("Random array with shape (3, 5) using np.random.randn():")
print(random_array)

Random array with shape (3, 5) using np.random.randn():
[[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337]
 [-0.23413696  1.57921282  0.76743473 -0.46947439  0.54256004]
 [-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]]


## Part 3: Indexing and Slicing

### Task 12
Create another array named `a`.


In [13]:
# 12. Create another array named a
a = np.array([
    [2, 7, 12, 0],
    [3, 9, 3, 4],
    [4, 0, 1, 3]
])

print("New array a:")
print(a)

New array a:
[[ 2  7 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


### Task 13
Retrieve the second row: `[3, 9, 3, 4]`.


In [14]:
# 13. Retrieve the second row
second_row = a[1]

print("Second row:")
print(second_row)

Second row:
[3 9 3 4]


### Task 14
Retrieve the third column: `[12, 3, 1]`.


In [15]:
# 14. Retrieve the third column
third_column = a[:, 2]

print("Third column:")
print(third_column)

Third column:
[12  3  1]


### Task 15
Create the required integer array and float array.


In [16]:
# 15. Create integer array
integer_array = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 2],
    [1, 6, 1, 1]
])

print("Integer array:")
print(integer_array)

Integer array:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 6 1 1]]


In [17]:
# 15. Create float array
float_array = np.array([
    [0., 0., 0., 0., 0.],
    [2., 0., 0., 0., 0.],
    [0., 3., 0., 0., 0.],
    [0., 0., 4., 0., 0.],
    [0., 0., 0., 5., 0.],
    [0., 0., 0., 0., 6.]
])

print("Float array:")
print(float_array)

Float array:
[[0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 6.]]


## Part 4: Boolean Masks and Statistics

### Task 16
Recall array `a`.


In [18]:
# 16. Recall array a
print("Original array a:")
print(a)

Original array a:
[[ 2  7 12  0]
 [ 3  9  3  4]
 [ 4  0  1  3]]


### Task 17
Use a comparison operation `> 5` to create a Boolean array.


In [19]:
# 17. Create Boolean mask for values greater than 5
mask = a > 5

print("Boolean mask where elements are greater than 5:")
print(mask)

Boolean mask where elements are greater than 5:
[[False  True  True False]
 [False  True False False]
 [False False False False]]


### Task 18
Use the mask to extract all values greater than 5.


In [20]:
# 18. Extract all values greater than 5
values_greater_than_5 = a[mask]

print("Values greater than 5:")
print(values_greater_than_5)

Values greater than 5:
[ 7 12  9]


### Task 19
Modify the array in-place so that all values greater than 5 are replaced with 5.


In [21]:
# 19. Modify the array in-place so values greater than 5 become 5
a[a > 5] = 5

print("Modified array a after replacing values greater than 5 with 5:")
print(a)

Modified array a after replacing values greater than 5 with 5:
[[2 5 5 0]
 [3 5 3 4]
 [4 0 1 3]]


## Part 5: Array Aggregation Functions

### Task 20
Using array `a` from earlier, compute the required aggregation values.

**Note:** Since Part 4 modifies `a` in-place, the aggregation below uses the modified version of `a`.


In [22]:
print("Using modified array a from Part 4:")
print(a)

Using modified array a from Part 4:
[[2 5 5 0]
 [3 5 3 4]
 [4 0 1 3]]


In [23]:
# 20a. Sum of all values
total_sum = np.sum(a)

print("20a. Sum of all values:")
print(total_sum)

20a. Sum of all values:
35


In [24]:
# 20b. Sum of each column
column_sum = np.sum(a, axis=0)

print("20b. Sum of each column:")
print(column_sum)

20b. Sum of each column:
[ 9 10  9  7]


In [25]:
# 20c. Sum of each row
row_sum = np.sum(a, axis=1)

print("20c. Sum of each row:")
print(row_sum)

20c. Sum of each row:
[12 15  8]


In [26]:
# 20d. Mean of all values
mean_value = np.mean(a)

print("20d. Mean of all values:")
print(mean_value)

20d. Mean of all values:
2.9166666666666665


In [27]:
# 20e. Minimum value
minimum_value = np.min(a)

print("20e. Minimum value:")
print(minimum_value)

20e. Minimum value:
0


In [28]:
# 20f. Maximum value
maximum_value = np.max(a)

print("20f. Maximum value:")
print(maximum_value)

20f. Maximum value:
5


## Lab 3 Completed

This notebook completes all required NumPy exercises for Lab 3.
